name = "hari-king"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "HARI_KV"
id = "TU_KV_ID_AQUI"

[[d1_databases]]
binding = "HARI_DB"
database_name = "hari-king-db"
database_id = "TU_D1_ID_AQUI"
